
exports.seed = function(knex, Promise) {
  return Promise.join(
    // Deletes ALL existing entries
    knex('listings').del(),

    // Inserts seed entries
    knex('listings').insert({
      heading:'Great Stow',
      renter_ID: ,
      lister_ID: 1,
      listerName: 'Gonzo',
      suburb:'Te Aro',
      city:'wellington',
      size:'1.5 * 2.5 m',
      price:10,
      description: 'a real beauty of spot',
      url: 'https://s-media-cache-ak0.pinimg.com/736x/72/fa/2d/72fa2d3b4d0c5d631c427dd0670d49c3.jpg',
      isAvailable:true,
      hasFeedback: false
    }),
    knex('listings').insert({
      heading:'Great location',
      renter_ID: ,
      lister_ID: 2,
      listerName: 'Big Bird',
      suburb:'Te Aro',
      city:'wellington',
      size:'3 * 3 m',
      price:13,
      description: 'a real beauty of spot',
      url: 'http://hsm-prod-designs.s3.amazonaws.com/wmFeJdz8ZN/f.jpg?hsid=AKBRGE1HGPGE2JL&ptype=3d',
      isAvailable:true,
      hasFeedback: false
    }),
    knex('listings').insert({
      heading:'Warm space,with a view!',
      renter_ID: ,
      lister_ID: 3,
      listerName: 'Oscar',
      suburb:'Aro Valley',
      city:'wellington',
      size:'2 * 3 m',
      price:15,
      description: 'a real beauty of spot',
      url: 'http://www.polyvore.com/cgi/img-thing?.out=jpg&size=l&tid=85911139',
      isAvailable:true,
      hasFeedback: false
    }),
    knex('listings').insert({
      heading:'place with a view',
      renter_ID: ,
      lister_ID: 4,
      listerName: 'Bert',
      suburb:'Thorndon',
      city:'wellington',
      size:'1 * 3 m',
      price:14,
      description: 'a real beauty of spot',
      url: 'http://activerain.com/image_store/uploads/7/4/8/0/7/ar124933531970847.JPG',
      isAvailable:true,
      hasFeedback: false
    }),
    knex('listings').insert({
      heading:'Great Stow,secure location',
      renter_ID: ,
      lister_ID: 5,
      listerName: 'Ernie',
      suburb:'Kilbirnie',
      city:'wellington',
      size:'1.5 * 3 m',
      price:8,
      description: 'a real beauty of spot',
      url: 'https://s-media-cache-ak0.pinimg.com/236x/c6/4b/01/c64b01cebf363a86e361667e3fae32b7.jpg',
      isAvailable:true,
      hasFeedback: false
    }),
    knex('listings').insert({
      heading:'Great Stow, secure location',
      renter_ID: ,
      lister_ID: 6,
      listerName: 'Kermit',
      suburb:'Oriental Bay',
      city:'wellington',
      size:'3 * 2 m',
      price:13,
      description: 'a real beauty of spot',
      url: 'http://1.bp.blogspot.com/_7romDtwkUxo/TU3Ih3_uUXI/AAAAAAAAAus/t040B7KeFkE/s1600/1st.jpg',
      isAvailable:true,
      hasFeedback: false
    }),
    knex('listings').insert({
      heading:'Secure and safe',
      renter_ID: ,
      lister_ID: 7,
      listerName: 'Snufaluffagus',
      suburb:'Aro Valley',
      city:'wellingtonwellington',
      size:'2 * 3 m',
      price:10,
      description: 'a real beauty of spot',
      url: 'http://www.qbikinsurance.com/wp-content/uploads/2013/12/bigstock-Empty-garage-with-metal-roll-u-25573682.jpg',
      isAvailable:true,
      hasFeedback: false
    }),
    knex('listings').insert({
      heading:'Great location',
      renter_ID: ,
      lister_ID: 8,
      listerName: 'Elmo',
      suburb:'Hataitai',
      city:'wellington',
      size:'4 * 3 m',
      price:17,
      description: 'a real beauty of spot',
      url: 'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQ01GaDrYtUpAPxNEdXCd3kj3m1t3TqaADDayuCYAxesyZZ7Q09ow',
      isAvailable:true,
      hasFeedback: false
    }),
    knex('listings').insert({
      heading:'Greatest stow in all of Winterfell',
      renter_ID: ,
      lister_ID: 9,
      listerName: 'Miss Piggy',
      suburb:'Mount Victoria',
      city:'wellington',
      size:'2.5 * 2.5 m',
      price:10,
      description: 'a real beauty of spot',
      url: 'https://media.licdn.com/mpr/mpr/shrinknp_800_800/AAEAAQAAAAAAAAMQAAAAJDdlYTYyNzZiLTZmMzMtNDg0Zi05MmQ4LTMwZmIxMzYxYzExMg.jpg',
      isAvailable:true,
      hasFeedback: false
    }),
    knex('listings').insert({
      heading:'Great Stow of Brooklyn',
      renter_ID: ,
      lister_ID: 10,
      listerName: "The Count",
      suburb:'Brooklyn',
      city:'wellington',
      size:'3 * 3 m',
      price:13,
      description: 'a real beauty of spot',
      url: 'http://i2.istockimg.com/file_thumbview_approve/69015185/5/stock-photo-69015185-blue-empty-room-with-parquet-floor.jpg',
      isAvailable:true,
      hasFeedback: false
    }),
    knex('listings').insert({
      heading:'Great Stow in the kitchen',
      renter_ID: ,
      lister_ID: 11,
      listerName: 'Cookie Monster',
      suburb:'Mount Cook',
      city:'wellington',
      size:'2 * 3 m',
      price:13,
      description: 'a real beauty of spot',
      url: 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcT1B6U8bHy_X75N1MtUwMiTVaKDLuCi2B07fSlgWYR8CSqtHrS9',
      isAvailable:true,
      hasFeedback: false
    }),
    knex('listings').insert({
      heading:'Greatest PokeStow',
      renter_ID: ,
      lister_ID: 12,
      listerName: 'Pikachu',
      suburb:'Mount Cook',
      city:'wellington',
      size:'2 * 5 m',
      price:13,
      description: 'a real beauty of spot',
      url: 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSVMewHMPxQhyeebK9JLI-cWkIcL7gjdZWASiy0VzKjKw8ddf0P',
      isAvailable:true,
      hasFeedback: false
    }),
    knex('listings').insert({
      heading:'Great Stow of the south',
      renter_ID: ,
      lister_ID: 13,
      listerName: "Kawasaki Jones",
      suburb:'Oriental Bay',
      city:'wellington',
      size:'1 * 3 m',
      price:7,
      description: 'a real beauty of spot',
      url: 'http://il6.picdn.net/shutterstock/videos/13970903/thumb/1.jpg',
      isAvailable:true,
      hasFeedback: false
    }),
    knex('listings').insert({
      heading:'Grand Stow',
      renter_ID: ,
      lister_ID: 14,
      listerName: 'SeaDoo Slayer',
      suburb:'Hataitai',
      city:'wellington',
      size:'2 * 3 m',
      price:15,
      description: 'a real beauty of spot',
      url: 'https://sizzlesays.files.wordpress.com/2012/06/empty-room.jpg',
      isAvailable:true,
      hasFeedback: false
    }),
    knex('listings').insert({
      heading:'Lots of room!!!',
      renter_ID:,
      lister_ID: 15,
      listerName: "morbiditytattler",
      suburb:'CBD',
      city:'auckland',
      size:'1 * 3 m',
      price:15,
      description: 'a real beauty of spot',
      url: 'http://www.gotoglamourgirl.com/wp-content/uploads/2011/01/empty-closet1.jpg',
      isAvailable:true,
      hasFeedback: false
    }),
    knex('listings').insert({
      heading:'Clean space',
      renter_ID: ,
      lister_ID:16 ,
      listerName: "hiddenshelduck",
      suburb:'Hauraki Gulf Islands ',
      city:'auckland',
      size:'3 * 3 m',
      price:15,
      description: 'a real beauty of spot',
      url: '',
      isAvailable:true,
      hasFeedback: false
    }),knex('listings').insert({
      heading:'Plenty of room',
      renter_ID: ,
      lister_ID: 17,
      listerName: "parmesaneyes",
      suburb:'Manukau ',
      city:'auckland',
      size:'1.5 * 3 m',
      price:8,
      description: 'a real beauty of spot',
      url: 'http://lightning.svaha.com/~simplysq/wp-content/uploads/2012/01/Closet-Empty-istock.jpg',
      isAvailable:true,
      hasFeedback: false
    }),knex('listings').insert({
      heading:'Very flexible',
      renter_ID: ,
      lister_ID: 18,
      listerName: "dustybasement",
      suburb:'Castor Bay',
      city:'auckland',
      size:'1 * 3 m',
      price:15,
      description: 'a real beauty of spot',
      url: 'http://3.bp.blogspot.com/-olO41QJN4hA/UFW5dqjLMLI/AAAAAAAAAqk/0mE_y0xGLpE/s1600/IMG_2844.JPG',
      isAvailable:true,
      hasFeedback: false
    }),knex('listings').insert({
      heading:'Climate control, clean',
      renter_ID: ,
      lister_ID: 19,
      listerName: "gobsmackedparka",
      suburb:'Manukau ',
      city:'auckland',
      size:'3 * 3 m',
      price:15,
      description: 'a real beauty of spot',
      url: 'https://upload.wikimedia.org/wikipedia/en/5/53/Century_House_Attic_West.JPG',
      isAvailable:true,
      hasFeedback: false
    }),knex('listings').insert({
      heading:'Nice stow',
      renter_ID: ,
      lister_ID: 20,
      listerName: "happitoe",
      suburb:'Hauraki Gulf Islands ',
      city:'auckland',
      size:'1.5 * 3 m',
      price:14,
      description: 'a real beauty of spot',
      url: 'http://homeinteriordesignthemes.com/wp-content/uploads/2009/09/attic-space-remodeling.jpg',
      isAvailable:true,
      hasFeedback: false
    }),knex('listings').insert({
      heading:'I have plenty of space',
      renter_ID: ,
      lister_ID: 21,
      listerName: "laptipper",
      suburb:'Awhitu',
      city:'auckland',
      size:'1 * 3 m',
      price:13,
      description: 'a real beauty of spot',
      url: 'http://image.shutterstock.com/z/stock-photo-empty-bedroom-with-an-empty-closet-62431162.jpg',
      isAvailable:true,
      hasFeedback: false
    }),knex('listings').insert({
      heading:'Nice place',
      renter_ID: ,
      lister_ID: 22,
      listerName: "slicky",
      suburb:'Manukau ',
      city:'auckland',
      size:'2 * 2 m',
      price:12,
      description: 'a real beauty of spot',
      url: 'https://s-media-cache-ak0.pinimg.com/236x/97/f4/3b/97f43b2989dbfbd076071f267363ccec.jpg',
      isAvailable:true,
      hasFeedback: false
    }),knex('listings').insert({
      heading:'big room, can have whole space',
      renter_ID: ,
      lister_ID: 23,
      listerName: "boatcomeboatgo",
      suburb:'Awhitu',
      city:'auckland',
      size:'1.5 * 3 m',
      price:19,
      description: 'a real beauty of spot',
      url: 'http://cdn.shopify.com/s/files/1/0543/8089/files/Attic_1_grande.jpg?4237899157731608921',
      isAvailable:true,
      hasFeedback: false
    }),knex('listings').insert({
      heading:'Perfect for inbetween moves',
      renter_ID: ,
      lister_ID: 24,
      listerName: "inbeforeGeorge",
      suburb:'Manukau ',
      city:'auckland',
      size:'1 * 3 m',
      price:17,
      description: 'a real beauty of spot',
      url: 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSnnJT2FWn5f_DAL-ldRf3QmUMNSiuI7ksqOjGErsL6zvXMXKRS',
      isAvailable:true,
      hasFeedback: false
    }),knex('listings').insert({
      heading:'Not that big, perfect for small furniture',
      renter_ID: ,
      lister_ID: 25,
      listerName: "stowin and flowin",
      suburb:'Hauraki Gulf Islands ',
      city:'auckland',
      size:'2 * 2 m',
      price:9,
      description: 'a real beauty of spot',
      url: 'http://st.hzcdn.com/simgs/8c9198a9002bb9d8_4-5327/traditional-family-room.jpg',
      isAvailable:true,
      hasFeedback: false
    }),knex('listings').insert({
      heading:'still room for more!!!',
      renter_ID: ,
      lister_ID: 26,
      listerName: "makemodel",
      suburb:'CBD',
      city:'auckland',
      size:'3 * 3 m',
      price:10,
      description: 'a real beauty of spot',
      url: 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSjq_naskUBsrMX51aHuduIvz-HwErbe3tzyQg8TkPP-QCbV2bl',
      isAvailable:true,
      hasFeedback: false
    }),knex('listings').insert({
      heading:'Great space',
      renter_ID: ,
      lister_ID: 27,
      listerName: "agaveking",
      suburb:'Franklin District',
      city:'auckland',
      size:'1 * 3 m',
      price:13,
      description: 'a real beauty of spot',
      url: 'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcReq20EiEpq9ZdfKkUPL8Y9GhdTsNYOD7EMI2dzlvDQ92C-qNGDtQ',
      isAvailable:true,
      hasFeedback: false
    }),knex('listings').insert({
      heading:'clean, climate control',
      renter_ID: ,
      lister_ID: 28,
      listerName: "idownit",
      suburb:'CBD',
      city:'auckland',
      size:'3 * 2 m',
      price:13,
      description: 'a real beauty of spot',
      url: 'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTxsn0Cm-9cZxDTBpKSKnQ_03QxaXwqiA5FemdthoIwX39D6kwg',
      isAvailable:true,
      hasFeedback: false
    }),knex('listings').insert({
      heading:'room for more',
      renter_ID: ,
      lister_ID: 29,
      listerName: "letitbetold",
      suburb:'Franklin District',
      city:'auckland',
      size:'1.5 * 3 m',
      price:20,
      description: 'a real beauty of spot',
      url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQtryOC4WaDlafTR9hPqQeDZrHJPEuyjxjR6ykjXR5LniYKz9FD',
      isAvailable:true,
      hasFeedback: false
    }),knex('listings').insert({
      heading:'perfect for a couch',
      renter_ID:,
      lister_ID: 30,
      listerName: "tooSpacy",
      suburb:'Bombay',
      city:'auckland',
      size:'3 * 2 m',
      price:14,
      description: 'a real beauty of spot',
      url: 'http://www.lundiausa.com/images/Home%20Storage%20Shelving%20Image%202%20250px.jpg',
      isAvailable:true,
      hasFeedback: false
    }),knex('listings').insert({
      heading:'im flexible, contact me',
      renter_ID: ,
      lister_ID: 31,
      listerName: "CBD",
      suburb:'auckland',
      city:'',
      size:'1 * 3 m',
      price:11,
      description: 'a real beauty of spot',
      url: 'http://ghk.h-cdn.co/assets/cm/15/11/54ffb1c892941-attic-storage-de.jpg',
      isAvailable:true,
      hasFeedback: false
    }),knex('listings').insert({
      heading:'Safe with me',
      renter_ID: ,
      lister_ID: 32,
      listerName: "spacecitystows",
      suburb:'CBD',
      city:'auckland',
      size:'3 * 2 m',
      price:13,
      description: 'a real beauty of spot',
      url: 'https://www.cranegardenbuildings.co.uk/uploads/images/00142/inside-30-x-36m-superior-shed-20m-eaves.jpg',
      isAvailable:true,
      hasFeedback: false
    }),knex('listings').insert({
      heading:'Highly reviewed, good price',
      renter_ID: ,
      lister_ID: 33,
      listerName: "bigboi12",
      suburb:'Castor Bay',
      city:'auckland',
      size:'1 * 3 m',
      price:10,
      description: 'a real beauty of spot',
      url: 'http://image.shutterstock.com/z/stock-photo-inside-of-a-heritage-tool-shed-61582882.jpg',
      isAvailable:true,
      hasFeedback: false
    }),knex('listings').insert({
      heading:'rent now!!',
      renter_ID: ,
      lister_ID: 34,
      listerName: "lostnfound",
      suburb:'Hauraki Gulf Islands ',
      city:'auckland',
      size:'1.5 * 3 m',
      price:12,
      description: 'a real beauty of spot',
      url: 'http://www.superiorsheds.com/wp-content/gallery/bungalow-shed-gallery/10x12-Bungalow-Inside.jpg',
      isAvailable:true,
      hasFeedback: false
    }),knex('listings').insert({
      heading:'great space',
      renter_ID: ,
      lister_ID: 35,
      listerName: "mylo44",
      suburb:'Central City',
      city:'christchurch',
      size:'2 * 2 m',
      price:,
      description: 'a real beauty of spot',
      url: 'http://www.fairdinkumsheds.co.nz/sites/default/files/uploads/shed_2_inside.jpg',
      isAvailable:true,
      hasFeedback: false
    }),knex('listings').insert({
      heading:'college students welcome',
      renter_ID: ,
      lister_ID: 36,
      listerName: "colt32",
      suburb:'Avonside',
      city:'christchurch',
      size:'1 * 3 m',
      price:,
      description: 'a real beauty of spot',
      url: 'http://basement.virginiawhalen.com/wp-content/uploads/2015/01/Basement-Storage-Shelves.jpg',
      isAvailable:true,
      hasFeedback: false
    }),knex('listings').insert({
      heading:'Will stow anything legal',
      renter_ID: ,
      lister_ID: 37,
      listerName: "zigzag",
      suburb:'Hei Hei',
      city:'christchurch',
      size:'2 * 2 m',
      price:,
      description: 'a real beauty of spot',
      url: 'http://photowizdesign.com/wp-content/uploads/2016/03/Striking-Meier-Road-Barn-Mork-Ulnes-Architects-Garage-and-Shed-Interior-Design-with-Neon-Ceiling-Lamps-on-Sloping.jpg',
      isAvailable:true,
      hasFeedback: false
    }),knex('listings').insert({
      heading:'Very clean stow',
      renter_ID: ,
      lister_ID: 38,
      listerName: "whereyaat",
      suburb:'Redcliffs',
      city:'christchurch',
      size:'3 * 2 m',
      price:,
      description: 'a real beauty of spot',
      url: 'https://s-media-cache-ak0.pinimg.com/736x/72/fa/2d/72fa2d3b4d0c5d631c427dd0670d49c3.jpg',
      isAvailable:true,
      hasFeedback: false
    }),knex('listings').insert({
      heading:'lots of space',
      renter_ID: ,
      lister_ID: 39,
      listerName: "atx4life",
      suburb:'Papanui',
      city:'christchurch',
      size:'2 * 2 m',
      price:12,
      description: 'a real beauty of spot',
      url: 'http://realsolutions.biz/files/2012/06/basement-storage.jpg',
      isAvailable:true,
      hasFeedback: false
    }),knex('listings').insert({
      heading:'Catch me stowin',
      renter_ID: ,
      lister_ID: 40,
      listerName: "kiwiclass",
      suburb:'Hornby',
      city:'christchurch',
      size:'1 * 3 m',
      price:13,
      description: 'a real beauty of spot',
      url: 'http://www.sheilazellerinteriors.com/wp-content/uploads/2011/06/2011-Basement-Shelving-001.png',
      isAvailable:true,
      hasFeedback: false
    })
  );
};
