
exports.seed = function(knex, Promise) {
  return Promise.join(
    // Deletes ALL existing entries
    knex('listings').del(),

    // Inserts seed entries
    knex('listings').insert({
      heading:'Great Stow',
      renter_ID: 1,
      lister_ID: 1,
      listerName: 'Gonzo',
      suburb:'Te Aro',
      city:'Wellington',
      size:'1.5 * 2.5 m',
      price:10,
      description: 'a real beauty of spot',
      url: 'https://s-media-cache-ak0.pinimg.com/736x/72/fa/2d/72fa2d3b4d0c5d631c427dd0670d49c3.jpg',
      isAvailable:true,
      hasFeedback: false
    }),
    knex('listings').insert({
      heading:'Great location',
      renter_ID: 3,
      lister_ID: 2,
      listerName: 'Big Bird',
      suburb:'Te Aro',
      city:'Wellington',
      size:'3 * 3 m',
      price:13,
      description: 'a real beauty of spot',
      url: 'http://hsm-prod-designs.s3.amazonaws.com/wmFeJdz8ZN/f.jpg?hsid=AKBRGE1HGPGE2JL&ptype=3d',
      isAvailable:true,
      hasFeedback: false
    }),
    knex('listings').insert({
      heading:'Warm space,with a view!',
      renter_ID: 3,
      lister_ID: 3,
      listerName: 'Oscar',
      suburb:'Aro Valley',
      city:'Wellington',
      size:'2 * 3 m',
      price:15,
      description: 'a real beauty of spot',
      url: 'http://www.polyvore.com/cgi/img-thing?.out=jpg&size=l&tid=85911139',
      isAvailable:true,
      hasFeedback: false
    }),
    knex('listings').insert({
      heading:'place with a view',
      renter_ID: 4,
      lister_ID: 4,
      listerName: 'Bert',
      suburb:'Thorndon',
      city:'Wellington',
      size:'1 * 3 m',
      price:14,
      description: 'a real beauty of spot',
      url: 'http://activerain.com/image_store/uploads/7/4/8/0/7/ar124933531970847.JPG',
      isAvailable:true,
      hasFeedback: false
    }),
    knex('listings').insert({
      heading:'Great Stow,secure location',
      renter_ID: 5,
      lister_ID: 5,
      listerName: 'Ernie',
      suburb:'Kilbirnie',
      city:'Wellington',
      size:'1.5 * 3 m',
      price:8,
      description: 'a real beauty of spot',
      url: 'https://s-media-cache-ak0.pinimg.com/236x/c6/4b/01/c64b01cebf363a86e361667e3fae32b7.jpg',
      isAvailable:true,
      hasFeedback: false
    }),
    knex('listings').insert({
      heading:'Great Stow, secure location',
      renter_ID: 6,
      lister_ID: 6,
      listerName: 'Kermit',
      suburb:'Oriental Bay',
      city:'Wellington',
      size:'3 * 2 m',
      price:13,
      description: 'a real beauty of spot',
      url: 'http://1.bp.blogspot.com/_7romDtwkUxo/TU3Ih3_uUXI/AAAAAAAAAus/t040B7KeFkE/s1600/1st.jpg',
      isAvailable:true,
      hasFeedback: false
    }),
    knex('listings').insert({
      heading:'Secure and safe',
      renter_ID: 7,
      lister_ID: 7,
      listerName: 'Snufaluffagus',
      suburb:'Aro Valley',
      city:'WellingtonWellington',
      size:'2 * 3 m',
      price:10,
      description: 'a real beauty of spot',
      url: 'http://www.qbikinsurance.com/wp-content/uploads/2013/12/bigstock-Empty-garage-with-metal-roll-u-25573682.jpg',
      isAvailable:true,
      hasFeedback: false
    }),
    knex('listings').insert({
      heading:'Great location',
      renter_ID: 8,
      lister_ID: 8,
      listerName: 'Elmo',
      suburb:'Hataitai',
      city:'Wellington',
      size:'4 * 3 m',
      price:17,
      description: 'a real beauty of spot',
      url: 'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQ01GaDrYtUpAPxNEdXCd3kj3m1t3TqaADDayuCYAxesyZZ7Q09ow',
      isAvailable:true,
      hasFeedback: false
    }),
    knex('listings').insert({
      heading:'Greatest stow in all of Winterfell',
      renter_ID: 9,
      lister_ID: 9,
      listerName: 'Miss Piggy',
      suburb:'Mount Victoria',
      city:'Wellington',
      size:'2.5 * 2.5 m',
      price:10,
      description: 'a real beauty of spot',
      url: 'https://media.licdn.com/mpr/mpr/shrinknp_800_800/AAEAAQAAAAAAAAMQAAAAJDdlYTYyNzZiLTZmMzMtNDg0Zi05MmQ4LTMwZmIxMzYxYzExMg.jpg',
      isAvailable:true,
      hasFeedback: false
    }),
    knex('listings').insert({
      heading:'Great Stow of Brooklyn',
      renter_ID: 10,
      lister_ID: 10,
      listerName: "The Count",
      suburb:'Brooklyn',
      city:'Wellington',
      size:'3 * 3 m',
      price:13,
      description: 'a real beauty of spot',
      url: 'http://i2.istockimg.com/file_thumbview_approve/69015185/5/stock-photo-69015185-blue-empty-room-with-parquet-floor.jpg',
      isAvailable:true,
      hasFeedback: false
    }),
    knex('listings').insert({
      heading:'Great Stow in the kitchen',
      renter_ID: 11,
      lister_ID: 11,
      listerName: 'Cookie Monster',
      suburb:'Mount Cook',
      city:'Wellington',
      size:'2 * 3 m',
      price:13,
      description: 'a real beauty of spot',
      url: 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcT1B6U8bHy_X75N1MtUwMiTVaKDLuCi2B07fSlgWYR8CSqtHrS9',
      isAvailable:true,
      hasFeedback: false
    }),
    knex('listings').insert({
      heading:'Greatest PokeStow',
      renter_ID: 12,
      lister_ID: 12,
      listerName: 'Pikachu',
      suburb:'Mount Cook',
      city:'Wellington',
      size:'2 * 5 m',
      price:13,
      description: 'a real beauty of spot',
      url: 'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcSVMewHMPxQhyeebK9JLI-cWkIcL7gjdZWASiy0VzKjKw8ddf0P',
      isAvailable:true,
      hasFeedback: false
    }),
    knex('listings').insert({
      heading:'Great Stow of the south',
      renter_ID: 13,
      lister_ID: 13,
      listerName: "Kawasaki Jones",
      suburb:'Oriental Bay',
      city:'Wellington',
      size:'1 * 3 m',
      price:7,
      description: 'a real beauty of spot',
      url: 'http://il6.picdn.net/shutterstock/videos/13970903/thumb/1.jpg',
      isAvailable:true,
      hasFeedback: false
    }),
    knex('listings').insert({
      heading:'Grand Stow',
      renter_ID: 14,
      lister_ID: 14,
      listerName: 'SeaDoo Slayer',
      suburb:'Hataitai',
      city:'Wellington',
      size:'2 * 3 m',
      price:15,
      description: 'a real beauty of spot',
      url: 'https://sizzlesays.files.wordpress.com/2012/06/empty-room.jpg',
      isAvailable:true,
      hasFeedback: false
    })
  );
};
